// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mission6Assignment.Models;

#nullable disable

namespace mission6Assignment.Migrations
{
    [DbContext(typeof(movieFormContext))]
    partial class movieFormContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("mission6Assignment.Models.MovieForm", b =>
                {
                    b.Property<int>("formID")
                        .HasColumnType("int")
                        .HasColumnName("formID");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("isEdited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lentTo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("movieCat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("movieDirector")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("movieRating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("movieTitle")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("movieTitle");

                    b.Property<int>("movieYear")
                        .HasColumnType("INTEGER");

                    b.HasKey("formID")
                        .HasName("PK_formID");

                    b.ToTable("Movies", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
